import org.springframework.boot.gradle.tasks.bundling.BootJar

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("multi.sca.java-common-conventions")
}

dependencies {
}

tasks.named<BootJar>("bootJar") {
    enabled = false
}