/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("multi.sca.java-common-conventions")
}

dependencies {
    implementation("org.springframework.cloud:spring-cloud-starter-loadbalancer")
    implementation("org.springframework.cloud:spring-cloud-starter-openfeign")
    implementation(project(":sca-api"))
}