/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("multi.sca.java-common-conventions")
}

dependencies {
    implementation("com.alibaba.cloud:spring-cloud-starter-alibaba-sentinel")
    implementation("com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config")
    implementation("org.springframework.cloud:spring-cloud-starter-loadbalancer")
    implementation("org.springframework.cloud:spring-cloud-starter-openfeign")
    implementation(project(":nacos:sca-api"))
}